In [1]:
import pandas as pd
import numpy as np

In [2]:
csv1 = pd.read_csv("9_tradeuniquecars.csv")

In [3]:
csv1

,Unnamed: 0,Make,Model,Price,Year,Transmission,Listing Type,Body Type,Fuel Type,Engine Capacity - Cc,Engine Power - KW
0,0,AC,COBRA,70000.0,1995.0,Automatic,Used,Soft Top,Premium Unleaded,4900.0,NaN
1,1,SUBARU,LIBERTY Gt,20000.0,1997.0,Manual,Used,Sedan,Unleaded,2000.0,NaN
2,2,TOYOTA,CAMRY,11500.0,2016.0,Automatic,Used,Sedan,NaN,NaN,V6
3,3,FORD,CORTINA TC 2 Door,57995.0,1972.0,Manual,Used,Hardtop - Coupe,Unleaded,1600.0,NaN
4,4,FORD,FALCON XF,15000.0,1985.0,Automatic,Used,Wagon,Unleaded,4100.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,CHEVROLET,BELAIR,NaN,1957.0,Automatic,Used,Hardtop - Coupe,NaN,NaN,NaN
1041,1041,PLYMOUTH,ROAD RUNNER TRIBUTE,NaN,1968.0,Automatic,Used,Hardtop - Coupe,NaN,NaN,NaN
1042,1042,AC,COBRA,NaN,2001.0,Manual,Used,Roadster,NaN,NaN,NaN
1043,1043,HSV,W427 VE,NaN,2009.0,NaN,Used,Sedan,NaN,NaN,NaN
1044,1044,CHEVROLET,CORVETTE C6,NaN,2008.0,Manual,Used,Hardtop - Coupe,NaN,NaN,377

In [4]:
csv2 = pd.read_csv("10_duttonrage.csv")

In [5]:
csv2

,Unnamed: 0,Make,Model,Price,Year
0,0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0
1,1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0
2,2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0
3,3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0
4,4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0
5,5,Mercedes-Benz,C-Class C205 C63 AMG S Coupe 2dr SPEEDSHIFT M...,NaN,2019.0
6,6,Maserati,Levante M161 Luxury Wagon 5dr Spts Auto 8sp Q...,10999000.0,2017.0
7,7,BMW,M4 F82 LCI Competition Coupe 2dr M-DCT 7sp 3.0TT,11999000.0,2019.0
8,8,Ferrari,348 sp Convertible 2dr Man 5sp 3.4i,21999000.0,2004.0
9,9,Porsche,Cayenne 9YA Wagon 5dr Tiptronic 8sp 4x4 3.0T ...,13999000.0,2019.0
10,10,Porsche,Cayenne 9YA Turbo Wagon 5dr Tiptronic 8sp 4x4...,NaN,2018.0
11,11,Mercedes-Benz,GLC-Class X253 GLC63 AMG S Wagon 5dr SPEEDSHI...,14499000.0,2019.0
12,12,Lexus,"LC URZ100R LC500 Coupe 2dr Spts Auto 10sp, 5....",NaN,2017.0
13,13,BMW,X5 G05 xDrive30d M Sport Wagon 5dr Steptronic...,10999000.0,2019.0
14,14,BMW,7 Series G12 750Li Sedan 4dr Steptronic 8sp 4...,11999000.0,2016.0
15,15,Tesla,Model S 85 Sportback 5dr Reduction Gear 1sp A...,6999000.0,2014.0
16,16,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,10499000.0,2017.0
17,17,Lamborghini,Gallardo L140 LP550-2 Coupe 2dr E-Gear 6sp 5.2i,24999000.0,2012.0
18,18,Mercedes-Benz,S-Class W223 S450 Sedan 4dr 9G-TRONIC 9sp 4MA...,26999000.0,2021.0
19,19,Porsche,Macan 95B GTS Wagon 5dr PDK 7sp AWD 3.0TT [MY18],10999000.0,2017.0
20,20,Mercedes-Benz,C-Class W205 C63 AMG S Sedan 4dr SPEEDSHIFT M...,15999000.0,2019.0
21,21,BMW,i8 I12 Coupe 2dr Auto 6sp AWD 1.5T/96kW Hybri...,17999000.0,2014.0
22,22,HARLEY DAVIDSON,FLHTCU ULTRA CLASSIC,2499000.0,2012.0
23,23,McLaren,600LT P13 Coupe 2dr SSG 7sp 3.8TT [MY19],46599000.0,2019.0
24,24,Mazda,RX-8 FE Series 2 Luxury Coupe 4dr Spts Auto 6...,4999000.0,2008.0
25,25,Mercedes-Benz,G-Class W463 G63 AMG Wagon 5dr SPEEDSHIFT 9sp...,30999000.0,2018.0
26,26,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,37499000.0,2009.0
27,27,Ferrari,612 Scaglietti F137 Coupe 2dr Seq. Mac 6sp 5.7i,19999000.0,2006.0
28,28,Bentley,Continental 3S GT Coupe 2dr DCT 8sp 4x4 6.0TT...,41999000.0,2019.0
29,29,McLaren,GT MA3 Coupe 2dr SSG 7sp 4.0TT [MY20],39999000.0,2020.0
30,30,Ferrari,599 Fiorano GTB Coupe 2dr Seq. Mac 6sp 6.0i [...,26999000.0,2006.0
31,31,Ferrari,488 Pista Spider F142 Convertible 2dr DCT 7sp...,99099000.0,2019.0
32,32,Ferrari,458 Speciale F142 Coupe 2dr DCT 7sp 4.5i,69999000.0,2015.0
33,33,Land Rover,Range Rover L405 SDV8 Vogue SE Wagon 5dr Spts...,18999000.0,2018.0
34,34,Porsche,Panamera 971 Turbo S E-Hybrid Sedan 4dr PDK 8...,29999000.0,2017.0
35,35,Porsche,911 996 GT2 Coupe 2dr Man 6sp 3.6TT [MY03],26999000.0,2004.0
36,36,Ferrari,F430 F136 Scuderia Coupe 2dr Seq. Mac 6sp 4.3i,54999000.0,2008.0
37,37,McLaren,675LT Coupe 2dr SSG 7sp 3.8TT [Jul],49999000.0,2015.0
38,38,Porsche,Carrera GT,NaN,2005.0
39,39,Ferrari,Enzo,NaN,2004.0
40,40,Maserati,MC12,NaN,2005.0
41,41,McLaren,650S Spider 2dr SSG 7sp 3.8TT [MY15],27999000.0,2014.0
42,42,NaN,Austin Healey 3000 Mk III Convertible 2dr Man ...,10999000.0,1967.0
43,43,Ferrari,330 GT 2+2 Coupe 2dr Man 5sp 4.0,NaN,1964.0
44,44,Ferrari,Testarossa Monospecchio,47999000.0,1986.0
45,45,NaN,Cooper BRM F2,NaN,NaN
46,46,Ferrari,328 GTS Coupe 2dr Man 5sp 3.2i,22999000.0,1987.0
47,47,Ferrari,F355 Spider Convertible 2dr Man 6sp 3.5i,29999000.0,1997.0
48,48,Mercedes-Benz,190SL R121 Roadster 2dr Man 4sp 1.9,31999000.0,1960.0
49,49,Mercedes-Benz,280SL Pagoda,NaN,1970.0
50,50,NaN,Jaguar E-Type 4.2 F H Coupe,NaN,1964.0
51,51,Porsche,356SC Coupe 2dr Man 4sp 1600,35999000.0,1964.0
52,52,Lamborghini,Miura P400 S,NaN,1969.0
53,53,Porsche,959,219999000.0,1987.0

In [6]:
csv1.drop(["Unnamed: 0"],axis=1,inplace=True)
csv2.drop(["Unnamed: 0"],axis=1,inplace=True)

In [7]:
import os
import glob
import pandas as pd
os.chdir("C:/Users/Dell/Downloads/EDA_Cars")

extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
print(all_filenames)

#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export to csv
combined_csv.to_csv( "cars_dataset.csv", index=False, encoding='utf-8-sig')

['10_duttonrage.csv', '9_tradeuniquecars.csv']

In [8]:
merged = pd.read_csv("cars_dataset.csv")
merged.drop(["Unnamed: 0"],axis =1 , inplace=True)

In [10]:
pd.read_csv("cars_dataset.csv")

,Unnamed: 0,Make,Model,Price,Year,Transmission,Listing Type,Body Type,Fuel Type,Engine Capacity - Cc,Engine Power - KW
0,0,Porsche,911 992 Carrera S Coupe 2dr PDK 8sp 3.0TT [MY21],NaN,2020.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,BMW,i8 I12 LCI Coupe 2dr Auto 6sp AWD 1.5T/105kW ...,NaN,2019.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Land Rover,Defender 90 Adventure Wagon 3dr Man 6sp 4x4 2...,10999000.0,2015.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Porsche,911 997 Series II Carrera Cabriolet 2dr PDK 7...,NaN,2009.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Porsche,Cayenne 9YB Turbo Coupe 5dr Tiptronic 8sp 4x4...,NaN,2020.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1094,1040,CHEVROLET,BELAIR,NaN,1957.0,Automatic,Used,Hardtop - Coupe,NaN,NaN,NaN
1095,1041,PLYMOUTH,ROAD RUNNER TRIBUTE,NaN,1968.0,Automatic,Used,Hardtop - Coupe,NaN,NaN,NaN
1096,1042,AC,COBRA,NaN,2001.0,Manual,Used,Roadster,NaN,NaN,NaN
1097,1043,HSV,W427 VE,NaN,2009.0,NaN,Used,Sedan,NaN,NaN,NaN
1098,1044,CHEVROLET,CORVETTE C6,NaN,2008.0,Manual,Used,Hardtop - Coupe,NaN,NaN,377